### PR TITLE
Bugfix: Creating request components, JSON serialization

### PR DESCRIPTION
**Pull request by trick14**
* Missed `scheme` when create `URLComponent`
* Missed `JSON Serialization`

### CODE REVIEW

**Comment by trick14** [comment]
@picomax can you give me an admin permission?

**Comment by picomax** [comment]
@trick14 
I have already designated you as a collaborator on this project.
I don't know if there are more levels of authority in github.
How can I give you an admin permission?

**Review by picomax — APPROVED** [review]
Thank you for your efforts.

**Comment by picomax** [comment]
Thank you for your efforts.

**Pull request closed without merging**
